export const complexityMap = {
    1: { time: 'O(n)', space: 'O(n)' },
    2: { time: 'O(n)', space: 'O(n)' },
    3: { time: 'O(n)', space: 'O(n)' },
    4: { time: 'O(n·k)', space: 'O(n·k)' },
    5: { time: 'O(n log k)', space: 'O(n)' },
    6: { time: 'O(n)', space: 'O(n)' },
    7: { time: 'O(n²)', space: 'O(n)' },
    8: { time: 'O(n)', space: 'O(n)' },
    9: { time: 'O(n)', space: 'O(n)' },
    10: { time: 'O(n)', space: 'O(1)' },
    11: { time: 'O(n)', space: 'O(1)' },
    12: { time: 'O(n²)', space: 'O(1)' },
    13: { time: 'O(n)', space: 'O(1)' },
    14: { time: 'O(n)', space: 'O(1)' },
    15: { time: 'O(n)', space: 'O(1)' },
    16: { time: 'O(n)', space: 'O(n)' },
    17: { time: 'O(n)', space: 'O(1)' },
    18: { time: 'O(n)', space: 'O(1)' },
    19: { time: 'O(n)', space: 'O(n)' },
    20: { time: 'O(n)', space: 'O(n)' },
    21: { time: 'O(n)', space: 'O(n)' },
    22: { time: 'O(1)', space: 'O(n)' },
    23: { time: 'O(n)', space: 'O(n)' },
    24: { time: 'O(2ⁿ)', space: 'O(n)' },
    25: { time: 'O(n)', space: 'O(n)' },
    26: { time: 'O(n log n)', space: 'O(n)' },
    27: { time: 'O(n)', space: 'O(n)' },
    28: { time: 'O(log n)', space: 'O(1)' },
    29: { time: 'O(log(m·n))', space: 'O(1)' },
    30: { time: 'O(n log m)', space: 'O(1)' },
    31: { time: 'O(log n)', space: 'O(1)' },
    32: { time: 'O(log n)', space: 'O(1)' },
    33: { time: 'O(log n)', space: 'O(n)' },
    34: { time: 'O(log(min(m,n)))', space: 'O(1)' },
    35: { time: 'O(n)', space: 'O(1)' },
    36: { time: 'O(n+m)', space: 'O(1)' },
    37: { time: 'O(n)', space: 'O(1)' },
    38: { time: 'O(n)', space: 'O(1)' },
    39: { time: 'O(n)', space: 'O(n)' },
    40: { time: 'O(max(n,m))', space: 'O(1)' },
    41: { time: 'O(n)', space: 'O(1)' },
    42: { time: 'O(n)', space: 'O(1)' },
    43: { time: 'O(1)', space: 'O(n)' },
    44: { time: 'O(n log k)', space: 'O(k)' },
    45: { time: 'O(n)', space: 'O(1)' },
    46: { time: 'O(n)', space: 'O(h)' },
    47: { time: 'O(n)', space: 'O(h)' },
    48: { time: 'O(n)', space: 'O(h)' },
    49: { time: 'O(n)', space: 'O(h)' },
    50: { time: 'O(n)', space: 'O(h)' },
    51: { time: 'O(n·m)', space: 'O(h)' },
    52: { time: 'O(h)', space: 'O(1)' },
    53: { time: 'O(n)', space: 'O(n)' },
    54: { time: 'O(n)', space: 'O(n)' },
    55: { time: 'O(n)', space: 'O(h)' },
    56: { time: 'O(n)', space: 'O(h)' },
    57: { time: 'O(h + k)', space: 'O(h)' },
    58: { time: 'O(n)', space: 'O(n)' },
    59: { time: 'O(n)', space: 'O(h)' },
    60: { time: 'O(n)', space: 'O(n)' },
    61: { time: 'O(L)', space: 'O(n·L)' },
    62: { time: 'O(L)', space: 'O(n·L)' },
    63: { time: 'O(n·m·4ᴸ)', space: 'O(L)' },
    64: { time: 'O(log k)', space: 'O(k)' },
    65: { time: 'O(n log n)', space: 'O(n)' },
    66: { time: 'O(n log k)', space: 'O(k)' },
    67: { time: 'O(n) avg', space: 'O(1)' },
    68: { time: 'O(n)', space: 'O(1)' },
    69: { time: 'O(n)', space: 'O(n)' },
    70: { time: 'O(log n)', space: 'O(n)' },
    71: { time: 'O(2ⁿ)', space: 'O(2ⁿ)' },
    72: { time: 'O(2ᵗ)', space: 'O(t)' },
    73: { time: 'O(n!)', space: 'O(n)' },
    74: { time: 'O(2ⁿ)', space: 'O(2ⁿ)' },
    75: { time: 'O(2ⁿ)', space: 'O(n)' },
    76: { time: 'O(n·m·4ᴸ)', space: 'O(L)' },
    77: { time: 'O(n·2ⁿ)', space: 'O(n)' },
    78: { time: 'O(4ⁿ·n)', space: 'O(n)' },
    79: { time: 'O(n!)', space: 'O(n²)' },
    80: { time: 'O(n·m)', space: 'O(n·m)' },
    81: { time: 'O(V+E)', space: 'O(V)' },
    82: { time: 'O(n·m)', space: 'O(n·m)' },
    83: { time: 'O(n·m)', space: 'O(n·m)' },
    84: { time: 'O(n·m)', space: 'O(n·m)' },
    85: { time: 'O(n·m)', space: 'O(n·m)' },
    86: { time: 'O(n·m)', space: 'O(n·m)' },
    87: { time: 'O(V+E)', space: 'O(V+E)' },
    88: { time: 'O(V+E)', space: 'O(V+E)' },
    89: { time: 'O(n)', space: 'O(n)' },
    90: { time: 'O(V+E)', space: 'O(V)' },
    91: { time: 'O(V+E)', space: 'O(V+E)' },
    92: { time: 'O(n·m²)', space: 'O(n·m)' },
    93: { time: 'O(E log E)', space: 'O(V+E)' },
    94: { time: 'O(n² log n)', space: 'O(n)' },
    95: { time: 'O(E log V)', space: 'O(V+E)' },
    96: { time: 'O(n² log n)', space: 'O(n²)' },
    97: { time: 'O(C)', space: 'O(V+E)' },
    98: { time: 'O(k·E)', space: 'O(V)' },
    99: { time: 'O(n)', space: 'O(1)' },
    100: { time: 'O(n)', space: 'O(1)' },
    101: { time: 'O(n)', space: 'O(1)' },
    102: { time: 'O(n)', space: 'O(1)' },
    103: { time: 'O(n²)', space: 'O(1)' },
    104: { time: 'O(n²)', space: 'O(1)' },
    105: { time: 'O(n)', space: 'O(1)' },
    106: { time: 'O(n·m)', space: 'O(m)' },
    107: { time: 'O(n)', space: 'O(1)' },
    108: { time: 'O(n³)', space: 'O(n)' },
    109: { time: 'O(n²)', space: 'O(n)' },
    110: { time: 'O(n·sum)', space: 'O(sum)' },
    111: { time: 'O(n·m)', space: 'O(m)' },
    112: { time: 'O(n·m)', space: 'O(n·m)' },
    113: { time: 'O(n)', space: 'O(1)' },
    114: { time: 'O(n·m)', space: 'O(m)' },
    115: { time: 'O(n·sum)', space: 'O(sum)' },
    116: { time: 'O(n·m)', space: 'O(n·m)' },
    117: { time: 'O(n·m)', space: 'O(n·m)' },
    118: { time: 'O(n·m)', space: 'O(n·m)' },
    119: { time: 'O(n·m)', space: 'O(n·m)' },
    120: { time: 'O(n³)', space: 'O(n²)' },
    121: { time: 'O(n·m)', space: 'O(n·m)' },
    122: { time: 'O(n)', space: 'O(1)' },
    123: { time: 'O(n)', space: 'O(1)' },
    124: { time: 'O(n)', space: 'O(1)' },
    125: { time: 'O(n)', space: 'O(1)' },
    126: { time: 'O(n log n)', space: 'O(n)' },
    127: { time: 'O(n)', space: 'O(1)' },
    128: { time: 'O(n)', space: 'O(n)' },
    129: { time: 'O(n)', space: 'O(1)' },
    130: { time: 'O(n)', space: 'O(n)' },
    131: { time: 'O(n log n)', space: 'O(n)' },
    132: { time: 'O(n log n)', space: 'O(1)' },
    133: { time: 'O(n log n)', space: 'O(1)' },
    134: { time: 'O(n log n)', space: 'O(n)' },
    135: { time: 'O(n log n)', space: 'O(n)' },
    136: { time: 'O(n²)', space: 'O(1)' },
    137: { time: 'O(n·m)', space: 'O(1)' },
    138: { time: 'O(n·m)', space: 'O(1)' },
    139: { time: 'O(log n)', space: 'O(1)' },
    140: { time: 'O(n)', space: 'O(1)' },
    141: { time: 'O(log n)', space: 'O(1)' },
    142: { time: 'O(n·m)', space: 'O(n+m)' },
    143: { time: 'O(n)', space: 'O(n)' },
    144: { time: 'O(n)', space: 'O(1)' },
    145: { time: 'O(1)', space: 'O(1)' },
    146: { time: 'O(n)', space: 'O(1)' },
    147: { time: 'O(1)', space: 'O(1)' },
    148: { time: 'O(n)', space: 'O(1)' },
    149: { time: 'O(1)', space: 'O(1)' },
    150: { time: 'O(log n)', space: 'O(1)' },
};
export const getComplexity = (id) => complexityMap[id] || { time: '—', space: '—' };
